import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../../core/routing/app_router.dart';
import '../../core/theme/app_colors.dart';

/// Scans a `tayo://invite/<token>` or `tayo://activate/<token>` QR code
/// (the same links generated by [family_screen.dart]'s share sheet) and
/// routes to the matching screen, reusing [pendingDeepLinkProvider] so the
/// rest of the app treats it identically to a tapped deep link.
class QrScanScreen extends ConsumerStatefulWidget {
  const QrScanScreen({super.key});

  @override
  ConsumerState<QrScanScreen> createState() => _QrScanScreenState();
}

class _QrScanScreenState extends ConsumerState<QrScanScreen> {
  final _controller = MobileScannerController();
  bool _handled = false;
  String? _error;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _onDetect(BarcodeCapture capture) {
    if (_handled) return;

    for (final barcode in capture.barcodes) {
      final raw = barcode.rawValue;
      if (raw == null) continue;

      final uri = Uri.tryParse(raw);
      if (uri == null || uri.scheme != 'tayo') continue;
      if (uri.host != 'invite' && uri.host != 'activate') continue;
      if (uri.pathSegments.isEmpty) continue;

      _handled = true;
      final token = uri.pathSegments.first;
      ref.read(pendingDeepLinkProvider.notifier).state = uri;
      context.go(uri.host == 'activate' ? '/activate/$token' : '/invite/$token');
      return;
    }

    setState(() => _error = "That code isn't a Tayo invite.");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        foregroundColor: Colors.white,
        elevation: 0,
        title: const Text('Scan invite code'),
      ),
      body: Stack(
        fit: StackFit.expand,
        children: [
          MobileScanner(controller: _controller, onDetect: _onDetect),
          Center(
            child: Container(
              width: 240,
              height: 240,
              decoration: BoxDecoration(
                border: Border.all(color: Colors.white, width: 2),
                borderRadius: BorderRadius.circular(20),
              ),
            ),
          ),
          Positioned(
            left: 24,
            right: 24,
            bottom: 40,
            child: Column(
              children: [
                Text(
                  'Point your camera at an invite or activation QR code',
                  textAlign: TextAlign.center,
                  style: Theme.of(context)
                      .textTheme
                      .bodyMedium
                      ?.copyWith(color: Colors.white),
                ),
                if (_error != null) ...[
                  const SizedBox(height: 8),
                  Text(
                    _error!,
                    textAlign: TextAlign.center,
                    style: const TextStyle(color: AppColors.danger),
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }
}
